{% set name = "argilla" %}
{% set version = "1.24.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/argilla-{{ version }}.tar.gz
  sha256: 76a45f9e576d1b503538a21383c860c693f50e010f1ee6fb4fddae978d3b5d2c

build:
  number: 1
  noarch: python
  entry_points:
    - argilla = argilla.cli.app:app
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0.0
    - pip
  run:
    - python >={{ python_min }},<3.12
    - httpx >=0.15,<=0.26
    - deprecated >=1.2.0,<1.3.dev0
    - packaging >=20.0
    - pandas >=1.0.0,<2.0.0
    - pydantic >=1.10.7
    - wrapt >=1.13,<1.15
    - numpy <1.24.0
    - tqdm >=4.27.0
    - backoff
    - monotonic
    - rich !=13.1.0
    - typer >=0.6.0,<0.10.0

test:
  imports:
    - argilla
  commands:
    - pip check
    - argilla --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://www.argilla.io/
  summary: Open-source tool for exploring, labeling, and monitoring data for NLP projects.
  license: Apache-2.0
  license_file: LICENSE
  description: |
    Argilla is an open-source platform for data-centric LLM development. 
    Integrates human and model feedback loops for continuous LLM refinement and oversight.

    With Argilla's Python SDK and adaptable UI, you can create human and model-in-the-loop workflows for:
    
    - Supervised fine-tuning
    - Preference tuning (RLHF, DPO, RLAIF, and more)
    - Small, specialized NLP models
    - Scalable evaluation.

    PyPI: [https://pypi.org/project/{{ name|lower }}/](https://pypi.org/project/{{ name|lower }}/)

    ---
    :fire: The conda-forge recipe was generated with [Conda-Forger App](https://sugatoray-conda-forger.streamlit.app/).
  
  dev_url: https://github.com/argilla-io/argilla
  doc_url: https://docs.argilla.io/

extra:
  recipe-maintainers:
    - sugatoray
